EQUIVALENCIAS_EQUIPOS = {
    "atletico mineiro mg": "atletico mineiro",
    "atlético mineiro-mg": "atletico mineiro",
    "atlético mineiro": "atletico mineiro",
    "se palmeiras sp": "palmeiras",
    "palmeiras-sp": "palmeiras",
    "fluminense fc rj": "fluminense",
    "fluminense-rj": "fluminense",
    "gremio fb porto alegrense rs": "gremio",
    "grêmio": "gremio",
    "grêmio-rs": "gremio",
    "coritiba-pr": "coritiba",
    "coritiba fc pr": "coritiba",
    "red bull bragantino sp": "bragantino",
    "rb bragantino-sp": "bragantino",
    "ec vitoria ba": "vitoria",
    "vitória-ba": "vitoria",
    "clube do remo pa": "remo",
    "remo-pa": "remo",
    "clube do remo": "remo",
    "internacional p. a.":"internacional",
    "sc internacional rs":"internacional",
    "sc internacional":"internacional",
    "athletico paranaense-pr":"athletico paranaense",
    "athletico-pr":"athletico paranaense",
    "ca paranaense pr":"athletico paranaense",
    "chapecoense-sc": "chapecoense",
    "chapecoense sc": "chapecoense",
    "santos fc sp": "santos",
    "santos-sp": "santos",
    "sc corinthians sp": "corinthians",
    "corinthians-sp": "corinthians",
    "sc corinthians paulista": "corinthians",
    "ec bahia ba": "bahia",
    "ec bahia": "bahia",
    "bahia-ba": "bahia",
    "sao paulo fc sp": "sao paulo",
    "são paulo-sp": "sao paulo",
    "sao paulo fc": "sao paulo",
    "cr flamengo rj": "flamengo",
    "flamengo-rj": "flamengo",
    "mirassol fc sp": "mirassol",
    "mirassol-sp": "mirassol",
    "cr vasco da gama rj": "vasco da gama",
    "vasco da gama-rj": "vasco da gama",
    "botafogo fr rj": "botafogo",
    "botafogo-rj": "botafogo",
    "botafogo rj": "botafogo",
    "cruzeiro ec mg": "cruzeiro",
    "cruzeiro-mg": "cruzeiro",
    "ceara sc ce": "ceara",
    "ec juventude rs": "juventude",
    "fortaleza ec ce": "fortaleza",
    "sc recife pe": "sport recife",
    "birmingham city": "birmingham",
    "blackburn rovers": "blackburn rovers",
    "bristol city": "bristol city",
    "charlton athletic": "charlton athletic",
    "coventry city": "coventry",
    "derby county": "derby county",
    "hull city": "hull city",
    "ipswich town": "ipswich town",
    "leicester city": "leicester city",
    "middlesbrough fc": "middlesbrough",
    "millwall fc": "millwall",
    "norwich city": "norwich city",
    "norwich": "norwich city",
    "oxford united": "oxford united",
    "portsmouth fc": "portsmouth",
    "preston north end": "preston",
    "queens park rangers": "queens park rangers",
    "sheffield united": "sheffield united",
    "sheffield wednesday": "sheffield wednesday",
    "southampton fc": "southampton",
    "stoke city": "stoke city",
    "swansea city": "swansea",
    "watford fc": "watford",
    "west bromwich albion": "west bromwich",
    "west brom": "west bromwich",
    "wrexham afc": "wrexham",
    "athletic bilbao": "athletic bilbao",
    "atletico madrid": "atletico madrid",
    "ca osasuna": "osasuna",
    "deportivo alaves": "alaves",
    "elche cf": "elche",
    "espanyol barcelona": "espanyol",
    "fc barcelona": "barcelona",
    "getafe cf": "getafe",
    "girona fc": "girona",
    "levante ud": "levante",
    "rayo vallecano": "rayo vallecano",
    "rc celta de vigo": "celta vigo",
    "rcd mallorca": "mallorca",
    "real betis seville": "real betis",
    "real betis balompie": "real betis",
    "real madrid": "real madrid",
    "real oviedo": "real oviedo",
    "real sociedad san sebastian": "real sociedad",
    "sevilla fc": "sevilla",
    "valencia cf": "valencia",
    "villarreal cf": "villarreal",
    "ad ceuta": "ceuta",
    "albacete balompie": "albacete",
    "burgos cf": "burgos",
    "cadiz cf": "cadiz",
    "cd castellon": "castellon",
    "cd leganes": "leganes",
    "cd mirandes": "mirandes",
    "cordoba cf": "cordoba",
    "cultural leonesa": "cultural leonesa",
    "fc andorra": "andorra",
    "granada cf": "granada",
    "malaga cf": "malaga",
    "racing santander": "racing santander",
    "rc deportivo la coruna": "deportivo la coruna",
    "real sociedad san sebastian b": "real sociedad b",
    "real valladolid": "real valladolid",
    "real zaragoza": "real zaragoza",
    "sd eibar": "eibar",
    "sd huesca": "huesca",
    "sporting gijon": "sporting de gijon",
    "ud almeria": "almeria",
    "ud las palmas": "las palmas",
    "alianza atletico": "alianza atletico",
    "alianza lima": "alianza lima",
    "asociacion deportiva tarma": "adt tarma",
    "atletico grau": "atletico grau",
    "ayacucho fc": "ayacucho",
    "comerciantes unidos": "comerciantes unidos",
    "cs cienciano": "cienciano",
    "csdc alianza universidad": "alianza universidad",
    "cusco fc": "cusco",
    "juan pablo ii college": "juan pablo ii",
    "los chankas cyc": "los chankas",
    "sport boys association": "sport boys",
    "sport huancayo": "sport huancayo",
    "sporting cristal": "sporting cristal",
    "universitario de deportes": "universitario",
    "utc de cajamarca": "utc cajamarca",
    "cd guadalajara": "chivas guadalajara",
    "cf america": "america",
    "cf cruz azul": "cruz azul",
    "cf monterrey": "monterrey",
    "cf pachuca": "pachuca",
    "club tijuana de caliente": "xolos de tijuana",
    "tijuana caliente": "xolos de tijuana",
    "fc juarez": "juarez",
    "deportivo toluca": "toluca",
    "pumas unam": "pumas unam",
    "tigres uanl": "tigres uanl",
    "aj auxerre": "auxerre",
    "angers sco": "angers",
    "as monaco": "monaco",
    "fc lorient": "lorient",
    "fc metz": "metz",
    "fc nantes": "nantes",
    "le havre ac": "le havre",
    "lille osc": "lille",
    "ogc nice": "niza",
    "olympique lyon": "lyon",
    "olympique marseille": "marsella",
    "paris fc": "paris fc",
    "paris saint germain": "paris saint germain",
    "paris saint-germain": "paris saint germain",
    "rc lens": "lens",
    "stade brest 29": "brest",
    "stade rennais fc": "rennes",
    "strasbourg alsace": "estrasburgo",
    "rc strasbourg": "estrasburgo",
    "toulouse fc": "toulouse",
    "fc cincinnati": "cincinnati",
    "inter miami cf": "inter miami",
    "minnesota united fc": "minnesota united",
    "new york city fc": "new york city",
    "philadelphia union": "philadelphia union",
    "san diego fc": "san diego",
    "afc bournemouth": "bournemouth",
    "arsenal fc": "arsenal",
    "aston villa": "aston villa",
    "brentford fc": "brentford",
    "brighton & hove albion": "brighton",
    "burnley fc": "burnley",
    "chelsea fc": "chelsea",
    "crystal palace": "crystal palace",
    "everton fc": "everton",
    "fulham fc": "fulham",
    "leeds united": "leeds",
    "liverpool fc": "liverpool",
    "manchester city": "manchester city",
    "manchester united": "manchester united",
    "newcastle united": "newcastle",
    "nottingham forest": "nottingham forest",
    "sunderland afc": "sunderland",
    "tottenham hotspur": "tottenham",
    "west ham united": "west ham",
    "wolverhampton wanderers": "wolves",
    "ac milan": "ac milan",
    "acf fiorentina": "fiorentina",
    "florenz": "fiorentina",
    "as roma": "roma",
    "atalanta bc": "atalanta",
    "bologna fc": "bologna",
    "cagliari calcio": "cagliari",
    "como 1907": "como",
    "genoa cfc": "genoa",
    "hellas verona": "verona",
    "inter milano": "inter de milan",
    "juventus turin": "juventus",
    "lazio rome": "lazio",
    "parma calcio": "parma",
    "parma calcio 1913": "parma",
    "pisa sc": "pisa",
    "sassuolo calcio": "sassuolo",
    "ssc napoli": "napoles",
    "torino fc": "torino",
    "turin": "torino",
    "udinese calcio": "udinese",
    "us cremonese": "cremonese",
    "us lecce": "lecce",
    "ajax amsterdam": "ajax",
    "bayer leverkusen": "bayer leverkusen",
    "bayern munich": "bayern munich",
    "bodoe glimt": "bodo glimt",
    "bodoe/glimt": "bodo glimt",
    "borussia dortmund": "borussia dortmund",
    "club brugge": "club brujas",
    "eintracht frankfurt": "eintracht frankfurt",
    "fc copenhagen": "copenhague",
    "fc kairat almaty": "kairat almaty",
    "galatasaray istanbul": "galatasaray",
    "olympiacos piraeus": "olympiakos piraeus",
    "pafos fc": "pafos",
    "psv eindhoven": "psv eindhoven",
    "qarabag fk": "qarabag",
    "sl benfica": "benfica",
    "slavia prague": "slavia prague",
    "sporting lisbon": "sporting lisboa",
    "sporting cp": "sporting lisboa",
    "union saint gilloise": "union saint gilloise",
    "1. fc cologne": "koln",
    "colonia": "koln",
    "1. fc heidenheim": "heidenheim",
    "borussia monchengladbach": "borussia monchengladbach",
    "fc augsburg": "augsburg",
    "fc st. pauli": "st. pauli",
    "fsv mainz": "mainz 05",
    "mainz": "mainz 05",
    "hamburger sv": "hamburgo",
    "rb leipzig": "leipzig",
    "sc freiburg": "freiburg",
    "friburgo": "freiburg",
    "tsg hoffenheim": "hoffenheim",
    "union berlin": "union berlin",
    "vfb stuttgart": "stuttgart",
    "vfl wolfsburg": "wolfsburgo",
    "werder bremen": "werder bremen",
    "augsburgo":"augsburg",
    "az alkmaar": "az alkmaar",
    "excelsior rotterdam": "excelsior",
    "fc groningen": "groningen",
    "fc twente enschede": "twente",
    "fc utrecht": "utrecht",
    "fc volendam": "volendam",
    "feyenoord rotterdam": "feyenoord",
    "fortuna sittard": "fortuna",
    "go ahead eagles": "ahead eagles",
    "heracles almelo": "heracles",
    "nac breda": "nac breda",
    "nec nijmegen": "nec nijmegen",
    "pec zwolle": "zwolle",
    "sc heerenveen": "heerenveen",
    "sc telstar": "telstar",
    "sparta rotterdam": "sparta rotterdam",
    "avs futebol sad": "avs futebol",
    "casa pia lisbon": "casa pia",
    "cd tondela": "tondela",
    "estoril praia": "estoril",
    "estrela amadora": "estrela amadora",
    "fc alverca sad": "alverca",
    "fc arouca": "arouca",
    "fc famalicao": "famalicao",
    "fc porto": "porto",
    "gil vicente barcelos": "gil vicente",
    "moreirense fc": "moreirense",
    "nacional da madeira": "nacional da madeira",
    "rio ave fc": "rio ave",
    "santa clara azores": "santa clara",
    "sc braga": "braga",
    "vitoria sc guimaraes": "vitoria guimaraes",
    "Aberdeen FC": "aberdeen",
    "AC Omonia Nicosia": "omonia nicosia",
    "AEK Athens": "aek atenas",
    "AEK Larnaca": "aek larnaca",
    "Breidablik Kopavogur": "breidablik kopavogur",
    "CS Universitatea Craiova": "universitatea craiova",
    "FC Dynamo Kyiv": "dynamo kiev",
    "FC Noah Yerevan": "noah",
    "FC Shakhtar Donetsk": "shakhtar donetsk",
    "FSV Mainz": "mainz 05",
    "Hacken Gothenburg": "bk hacken",
    "Hamrun Spartans FC": "hamrun spartan",
    "HNK Rijeka": "rijeka",
    "HSK Zrinjski Mostar": "zrinjski",
    "Jagiellonia Bialystok": "jagiellonia bialystok",
    "KF Drita": "drita",
    "KKS Lech Poznan": "lech poznan",
    "Kuopion Palloseura": "kups",
    "Lausanne-Sport": "lausanne sport",
    "Legia Warszawa": "legia varsovia",
    "Lincoln Red Imps": "lincoln red imps",
    "NK Celje": "celje",
    "Rayo Vallecano": "rayo vallecano",
    "RKS Rakow Czestochowa": "rakow czestochowa",
    "Samsunspor": "samsunspor",
    "Shamrock Rovers": "shamrock rovers",
    "Shelbourne FC": "shelbourne",
    "Shkendija Tetovo": "shkendija",
    "SK Rapid": "rapid de viena",
    "SK Sigma Olomouc": "sigma olomouc",
    "SK Slovan Bratislava": "slovan bratislava",
    "Sparta Prague": "sparta praga",
    "celtic glasgow": "celtic",
    "fc basel 1893": "basel",
    "fc midtjylland": "midtjylland",
    "fc salzburg": "salzburg",
    "fc viktoria plzen": "viktoria plzen",
    "fenerbahce istanbul": "fenerbahce",
    "ferencvarosi budapest": "ferencvaros",
    "fk crvena zvezda belgrade": "crvena zvezda",
    "fotbal club fcsb": "fotbal club fcsb",
    "glasgow rangers": "rangers fc",
    "gnk dinamo zagreb": "dinamo zagreb",
    "krc genk": "krc genk",
    "maccabi tel aviv fc": "maccabi tel aviv",
    "malmo ff": "malmo",
    "panathinaikos athens": "panathinaikos",
    "paok thessaloniki": "paok",
    "pfc ludogorets 1945 razgrad": "ludogorets",
    "sk brann": "brann",
    "sk sturm graz": "sturm",
    "young boys bern": "young boys",
    "adt de tarma": "adt tarma",
    "alianza universidad": "alianza universidad",
    "ayacucho": "ayacucho",
    "chankas cyc": "los chankas",
    "cienciano": "cienciano",
    "juan pablo ii": "juan pablo ii",
    "sport boys": "sport boys",
    "utc cajamarca": "utc cajamarca",
    "afc ajax": "ajax",
    "atletico de madrid": "atletico madrid",
    "bayer 04 leverkusen": "bayer leverkusen",
    "bayern munchen": "bayern munich",
    "chelsea": "chelsea",
    "club brugge kv": "club brujas",
    "fk bodo glimt": "bodo glimt",
    "galatasaray sk": "galatasaray",
    "inter milan": "inter de milan",
    "juventus": "juventus",
    "kairat almaty": "kairat almaty",
    "marsella": "marsella",
    "napoles": "napoles",
    "olympiacos fc": "olympiakos piraeus",
    "sporting lisboa": "sporting lisboa",
    "aston villa fc": "aston villa",
    "basel": "basel",
    "brann": "brann",
    "bsc young boys": "young boys",
    "celtic fc": "celtic",
    "estrella roja": "crvena zvezda",
    "fcsb": "fotbal club fcsb",
    "fenerbahce": "fenerbahce",
    "ferencvaros tc": "ferencvaros",
    "feyenoord": "feyenoord",
    "gnk dinamo": "dinamo zagreb",
    "losc lille": "lille",
    "ogc niza": "niza",
    "panathinaikos": "panathinaikos",
    "paok fc": "paok",
    "pfc ludogorets": "ludogorets",
    "rangers fc": "rangers fc",
    "rangers": "rangers fc",
    "rc celta": "celta vigo",
    "real betis": "real betis",
    "utrecht": "utrecht",
    "1 fsv mainz 05": "mainz 05",
    "aberdeen fc": "aberdeen",
    "ac omonia nicosia": "omonia nicosia",
    "ac sparta prague": "sparta praga",
    "aek": "aek atenas",
    "aek larnaca": "aek larnaca",
    "bk hacken": "bk hacken",
    "breidablik kopavogur": "breidablik kopavogur",
    "celje": "celje",
    "drita": "drita",
    "estrasburgo": "estrasburgo",
    "fc dynamo kiev": "dynamo kiev",
    "fc lausanne sports": "lausanne sport",
    "fc shakhtar donetsk": "shakhtar donetsk",
    "fiorentina": "fiorentina",
    "hamrun spartan": "hamrun spartan",
    "jagiellonia bialystok": "jagiellonia bialystok",
    "kups": "kups",
    "lech poznan": "lech poznan",
    "legia warszawa": "legia varsovia",
    "lincoln red imps fc": "lincoln red imps",
    "noah": "noah",
    "rakow czestochowa": "rakow czestochowa",
    "rapid wien": "rapid de viena",
    "rijeka": "rijeka",
    "samsunspor": "samsunspor",
    "shamrock rovers fc": "shamrock rovers",
    "shelbourne fc": "shelbourne",
    "shkendija": "shkendija",
    "sigma olomouc": "sigma olomouc",
    "sk slovan bratislava": "slovan bratislava",
    "u craiova": "universitatea craiova",
    "zrinjski": "zrinjski",
    "flamengo": "flamengo",
    "palmeiras": "palmeiras",
    "elche": "elche",
    "levante": "levante",
    "rcd espanyol": "espanyol",
    "real sociedad": "real sociedad",
    "albacete": "albacete",
    "almeria": "almeria",
    "andorra": "andorra",
    "burgos": "burgos",
    "cadiz": "cadiz",
    "castellon": "castellon",
    "cordoba": "cordoba",
    "deportivo la coruna": "deportivo la coruna",
    "eibar": "eibar",
    "granada": "granada",
    "huesca": "huesca",
    "malaga": "malaga",
    "mirandes": "mirandes",
    "real sociedad b": "real sociedad b",
    "real sporting de gijon": "sporting de gijon",
    "bournemouth": "bournemouth",
    "brighton hove albion": "brighton",
    "burnley": "burnley",
    "everton": "everton",
    "fulham": "fulham",
    "leeds": "leeds",
    "sunderland": "sunderland",
    "birmingham": "birmingham",
    "coventry": "coventry",
    "fc middlesbrough": "middlesbrough",
    "millwall": "millwall",
    "norwich city fc": "norwich city",
    "portsmouth": "portsmouth",
    "preston": "preston",
    "sheffield united fc": "sheffield united",
    "swansea": "swansea",
    "watford": "watford",
    "west bromwich": "west bromwich",
    "wrexham": "wrexham",
    "cagliari": "cagliari",
    "como": "como",
    "cremonese": "cremonese",
    "genoa": "genoa",
    "lecce": "lecce",
    "parma": "parma",
    "pisa": "pisa",
    "sassuolo": "sassuolo",
    "ss lazio": "lazio",
    "torino": "torino",
    "udinese": "udinese",
    "verona": "verona",
    "venezia": "venezia",
    "1 fc heidenheim 1846": "heidenheim",
    "1 fc union berlin": "union berlin",
    "fc koln": "koln",
    "fc st pauli": "st pauli",
    "hamburg": "hamburgo",
    "sv werder bremen": "werder bremen",
    "angers": "angers",
    "auxerre": "auxerre",
    "le havre": "le havre",
    "lens": "lens",
    "lorient": "lorient",
    "metz": "metz",
    "nantes": "nantes",
    "rennes": "rennes",
    "stade brestois 29": "brest",
    "toulouse": "toulouse",
    "atletico mg": "atletico mineiro",
    "bahia": "bahia",
    "botafogo": "botafogo",
    "bragantino": "bragantino",
    "ceara": "ceara",
    "corinthians": "corinthians",
    "cruzeiro": "cruzeiro",
    "ec juventude": "juventude",
    "fluminense": "fluminense",
    "fortaleza": "fortaleza",
    "gremio": "gremio",
    "internacional": "internacional",
    "mirassol": "mirassol",
    "santos": "santos",
    "sao paulo fc": "sao paulo",
    "sport recife": "sport recife",
    "vasco da gama": "vasco da gama",
    "alverca": "alverca",
    "arouca": "arouca",
    "casa pia": "casa pia",
    "estoril": "estoril",
    "famalicao": "famalicao",
    "gil vicente": "gil vicente",
    "moreirense": "moreirense",
    "nacional": "nacional da madeira",
    "rio ave": "rio ave",
    "santa clara": "santa clara",
    "tondela": "tondela",
    "vitoria guimaraes": "vitoria guimaraes",
    "excelsior": "excelsior",
    "fortuna": "fortuna",
    "groningen": "groningen",
    "heerenveen": "heerenveen",
    "heracles": "heracles",
    "nec": "nec nijmegen",
    "sparta de roterdam": "sparta rotterdam",
    "telstar": "telstar",
    "volendam": "volendam",
    "zwolle": "zwolle",
    "america": "america",
    "cruz azul": "cruz azul",
    "guadalajara chivas": "chivas guadalajara",
    "juarez": "juarez",
    "monterrey": "monterrey",
    "pachuca": "pachuca",
    "xolos de tijuana": "xolos de tijuana",
    "los angeles fc": "los angeles",
    "new york city": "new york city",
    "vancouver whitecaps": "vancouver",
    "atletico mineiro": "atletico mineiro",
    "stuttgart": "stuttgart",
    "wolfsburg": "wolfsburgo",
    "bolonia fc": "bologna",
    "genova": "genoa",
    "lanus": "lanus",
    "stade brestois": "brest",
    "benfica": "benfica",
    "club brujas": "club brujas",
    "qarabag": "qarabag",
    "fc shakhtar": "shakhtar donetsk",
    "slovan bratislava": "slovan bratislava",
    "sturm": "sturm",
    "tarma": "adt tarma",
    "red star": "crvena zvezda",
    "chivas guadalajara": "chivas guadalajara",
    "club america": "america",
    "club tijuana": "xolos de tijuana",
    "brest": "brest",
    "lille": "lille",
    "lyon": "lyon",
    "niza": "niza",
    "psg": "paris saint germain",
    "atalanta": "atalanta",
    "bolonia": "bologna",
    "inter": "inter de milan",
    "lazio": "lazio",
    "roma": "roma",
    "ajax": "ajax",
    "fc twente": "twente",
    "ad ceuta fc": "ceuta",
    "leganes": "leganes",
    "sporting de gijon": "sporting de gijon",
    "valladolid": "real valladolid",
    "arsenal": "arsenal",
    "bodø glimt": "bodo glimt",
    "fc copenhague": "copenhague",
    "galatasaray": "galatasaray",
    "liverpool": "liverpool",
    "olympiakos piraeus": "olympiakos piraeus",
    "slavia praga": "slavia prague",
    "tottenham": "tottenham",
    "villarreal": "villarreal",
    "1. fc koln": "koln",
    "1. fc union berlin": "union berlin",
    "hamburgo": "hamburgo",
    "mainz 05": "mainz 05",
    "bahia ba": "bahia",
    "botafogo rj": "botafogo",
    "ceara ce": "ceara",
    "corinthians sp": "corinthians",
    "cruzeiro mg": "cruzeiro",
    "flamengo rj": "flamengo",
    "fluminense rj": "fluminense",
    "fortaleza ce": "fortaleza",
    "gremio rs": "gremio",
    "juventude rs": "juventude",
    "mirassol sp": "mirassol",
    "palmeiras sp": "palmeiras",
    "rb bragantino sp": "bragantino",
    "santos sp": "santos",
    "sao paulo sp": "sao paulo",
    "sport recife pe": "sport recife",
    "vasco da gama rj": "vasco da gama",
    "vitoria ba": "vitoria",
    "alaves": "alaves",
    "celta vigo": "celta vigo",
    "espanyol": "espanyol",
    "getafe": "getafe",
    "girona": "girona",
    "mallorca": "mallorca",
    "osasuna": "osasuna",
    "sevilla": "sevilla",
    "valencia": "valencia",
    "basilea": "basel",
    "celtic": "celtic",
    "crvena zvezda": "crvena zvezda",
    "dinamo zagreb": "dinamo zagreb",
    "ferencvaros": "ferencvaros",
    "ludogorets razgrad": "ludogorets",
    "maccabi tel aviv": "maccabi tel aviv",
    "red bull salzburg": "salzburg",
    "s.c. braga": "braga",
    "sturm graz": "sturm",
    "viktoria plzen": "viktoria plzen",
    "young boys": "young boys",
    "cd los chankas": "los chankas",
    "cienciano cusco": "cienciano",
    "brentford": "brentford",
    "brighton": "brighton",
    "west ham": "west ham",
    "wolves": "wolves",
    "middlesbrough": "middlesbrough",
    "southampton": "southampton",
    "aberdeen": "aberdeen",
    "aek atenas": "aek atenas",
    "breiðablik": "breidablik kopavogur",
    "dynamo kyiv": "dynamo kiev",
    "fc noah": "noah",
    "fk shkendija": "shkendija",
    "hamrun spartans": "hamrun spartan",
    "jagiellonia białystok": "jagiellonia białystok",
    "kf drita": "drita",
    "lausanne sport": "lausanne sport",
    "legia varsovia": "legia varsovia",
    "nk celje": "celje",
    "omonia nicosia": "omonia nicosia",
    "rapid de viena": "rapid de viena",
    "shakhtar donetsk": "shakhtar donetsk",
    "shamrock rovers": "shamrock rovers",
    "shelbourne": "shelbourne",
    "sparta praga": "sparta praga",
    "universitatea craiova": "universitatea craiova",
    "zrinjski mostar": "zrinjski",
    "Atalanta": "atalanta",
    "Bolonia": "bologna",
    "Cagliari": "cagliari",
    "Genoa": "genoa",
    "Inter": "inter de milan",
    "Juventus": "juventus",
    "Lazio": "lazio",
    "Napoles": "napoles",
    "Parma": "parma",
    "Udinese": "udinese",
    "o higgins":"ohiggins",
    "o'higgins":"ohiggins",
    "bahia-ba":"bahia",
    "avs":"avs Futebol",
    "dep la coruna":"deportivo la coruna",
    "venezia": "venezia",
    "ssc neapel": "napoles",
    "roter stern belgrad": "crvena zvezda",
    "paok saloniki": "paok",
    "racing lens": "lens",
    "stade rennes": "rennes",
    "cd tolima": "deportes tolima",
    "la galaxy": "los angeles galaxy",
    "saint louis city": "saint louis city",
    "st. louis city": "saint louis city",
    "wolverhampton": "Wolves",
    "napoli": "napoles",
    "aek athen": "aek atenas",
    "strasbourg": "estrasburgo",
}