EQUIVALENCIAS_EQUIPOS = {
    "west ham": "west ham",
    "sunderland": "sunderland",
    "burnley": "burnley",
    "tottenham": "tottenham",
    "fulham": "fulham",
    "brighton": "brighton",
    "man city": "manchester city",
    "wolves": "wolves",
    "bournemouth": "bournemouth",
    "liverpool": "liverpool",
    "brentford": "brentford",
    "nottm forest": "nottingham forest",
    "crystal palace": "crystal palace",
    "chelsea": "chelsea",
    "newcastle": "newcastle",
    "aston villa": "aston villa",
    "arsenal": "arsenal",
    "man utd": "manchester united",
    "everton": "everton",
    "leeds": "leeds",
    "atletico mg": "atletico mineiro",
    "se palmeiras": "palmeiras",
    "coritiba": "coritiba",
    "red bull bragantino": "bragantino",
    "ec vitoria salvador": "vitoria",
    "remo": "remo",
    "internacional": "internacional",
    "athletico-pr": "athletico paranaense",
    "fluminense": "fluminense",
    "gremio": "gremio",
    "chapecoense": "chapecoense",
    "santos": "santos",
    "corinthians": "corinthians",
    "bahia": "bahia",
    "mirassol": "mirassol",
    "vasco da gama": "vasco da gama",
    "sao paulo": "sao paulo",
    "flamengo": "flamengo",
    "botafogo fr": "botafogo",
    "cruzeiro mg": "cruzeiro",
    "st pauli": "st. pauli",
    "hamburger sv": "hamburgo",
    "bayern munich": "bayern munich",
    "augsburg": "augsburg",
    "eintracht frankfurt": "eintracht frankfurt",
    "hoffenheim": "hoffenheim",
    "fc heidenheim": "heidenheim",
    "rb leipzig": "leipzig",
    "leverkusen": "bayer leverkusen",
    "werder bremen": "werder bremen",
    "mainz": "mainz 05",
    "wolfsburg": "wolfsburgo",
    "union berlin": "union berlin",
    "dortmund": "borussia dortmund",
    "mgladbach": "borussia monchengladbach",
    "stuttgart": "stuttgart",
    "freiburg": "freiburg",
    "fc koln": "koln",
    "derby": "derby county",
    "west brom": "west bromwich",
    "middlesbrough": "middlesbrough",
    "preston": "preston",
    "millwall": "millwall",
    "charlton": "charlton athletic",
    "birmingham": "birmingham",
    "stoke": "stoke city",
    "blackburn": "blackburn rovers",
    "watford": "watford",
    "bristol city": "bristol city",
    "sheff wed": "sheffield wednesday",
    "hull": "hull city",
    "swansea": "swansea",
    "leicester": "leicester city",
    "oxford utd": "oxford united",
    "qpr": "queens park rangers",
    "wrexham": "wrexham",
    "sheff utd": "sheffield united",
    "ipswich": "ipswich town",
    "portsmouth": "portsmouth",
    "southampton": "southampton",
    "norwich": "norwich city",
    "coventry": "coventry",
    "hertha berlin": "hertha berlin",
    "holstein kiel": "holstein kiel",
    "ajax": "ajax",
    "fc volendam": "volendam",
    "nec nijmegen": "nec nijmegen",
    "pec zwolle": "zwolle",
    "psv": "psv eindhoven",
    "nac breda": "nac breda",
    "fc twente": "twente",
    "excelsior": "excelsior",
    "sc telstar": "telstar",
    "az alkmaar": "az alkmaar",
    "fc groningen": "groningen",
    "fortuna sittard": "fortuna",
    "fc utrecht": "utrecht",
    "sparta rotterdam": "sparta rotterdam",
    "feyenoord": "feyenoord",
    "heracles": "heracles",
    "burton albion": "burton albion",
    "mansfield": "mansfield",
    "grimsby": "grimsby",
    "wigan": "wigan",
    "macclesfield": "macclesfield",
    "levante": "levante",
    "elche": "elche",
    "rayo vallecano": "rayo vallecano",
    "osasuna": "osasuna",
    "valencia": "valencia",
    "espanyol": "espanyol",
    "sevilla": "sevilla",
    "athletic bilbao": "athletic bilbao",
    "villarreal": "villarreal",
    "real madrid": "real madrid",
    "atletico madrid": "atletico madrid",
    "mallorca": "mallorca",
    "barcelona": "barcelona",
    "oviedo": "real oviedo",
    "real sociedad": "real sociedad",
    "celta vigo": "celta vigo",
    "alaves": "alaves",
    "betis": "real betis",
    "girona": "girona",
    "getafe": "getafe",
    "malaga": "malaga",
    "burgos": "burgos",
    "valladolid": "real valladolid",
    "albacete": "albacete",
    "leganes": "leganes",
    "sociedad b": "real sociedad b",
    "las palmas": "las palmas",
    "cordoba": "cordoba",
    "sporting gijon": "sporting de gijon",
    "mirandes": "mirandes",
    "cadiz": "cadiz",
    "granada": "granada",
    "andorra cf": "andorra",
    "huesca": "huesca",
    "eibar": "eibar",
    "almeria": "almeria",
    "zaragoza": "real zaragoza",
    "cd castellon": "castellon",
    "deportivo": "deportivo la coruna",
    "racing santander": "racing santander",
    "ad ceuta fc": "ceuta",
    "leonesa": "cultural leonesa",
    "auxerre": "auxerre",
    "paris st-g": "paris saint germain",
    "rennes": "rennes",
    "lorient": "lorient",
    "le havre": "le havre",
    "monaco": "monaco",
    "marseille": "marsella",
    "lens": "lens",
    "nantes": "nantes",
    "nice": "niza",
    "brest": "brest",
    "toulouse": "toulouse",
    "metz": "metz",
    "lyon": "lyon",
    "paris fc": "paris fc",
    "angers": "angers",
    "lille": "lille",
    "strasbourg": "estrasburgo",
    "casa pia": "casa pia",
    "avs futebol sad": "avs Futebol",
    "moreirense": "moreirense",
    "santa clara": "santa clara",
    "arouca": "arouca",
    "sporting lisbon": "sporting lisboa",
    "estoril praia": "estoril",
    "guimaraes": "vitoria guimaraes",
    "cd nacional funchal": "nacional da madeira",
    "rio ave": "rio ave",
    "benfica": "benfica",
    "club football estrela": "estrela amadora",
    "famalicao": "famalicao",
    "tondela": "tondela",
    "porto": "porto",
    "gil vicente": "gil vicente",
    "inter": "inter de milan",
    "pisa": "pisa",
    "como": "como",
    "torino": "torino",
    "fiorentina": "fiorentina",
    "cagliari": "cagliari",
    "lecce": "lecce",
    "lazio": "lazio",
    "sassuolo": "sassuolo",
    "us cremonese": "cremonese",
    "atalanta": "atalanta",
    "parma": "parma",
    "genoa": "genoa",
    "bologna": "bologna",
    "juventus": "juventus",
    "napoli": "napoles",
    "roma": "roma",
    "ac milan": "ac milan",
    "verona": "verona",
    "udinese": "udinese",
    "olympiakos": "olympiakos piraeus",
    "kairat almaty": "kairat almaty",
    "bodo glimt": "bodo glimt",
    "fc copenhagen": "copenhague",
    "club brugge": "club brujas",
    "qarabag fk": "qarabag",
    "galatasaray": "galatasaray",
    "pafos fc": "pafos",
    "slavia prague": "slavia prague",
    "union st gilloise": "union saint gilloise",
    "plzen": "viktoria plzen",
    "genk": "krc genk",
    "malmo ff": "malmo",
    "rangers": "rangers fc",
    "la galaxy": "los angeles galaxy",
    "dc utd": "dc united",
    "kansas city": "sporting kansas city",
    "colorado": "colorado rapids",
    "st louis city sc": "saint louis city",
    "new england": "new england revolution",
    "vancouver whitecaps": "vancouver",
    "minnesota utd": "minnesota united",
    "tijuana": "xolos de tijuana",
    "tigres": "tigres uanl",
    "sport boys (per)": "sport boys",
    "melgar": "fbc melgar",
    "cesar vallejo moquegua": "cd moquegua",
    "algeria": "algeria",
    "argentina": "argentina",
    "australia": "australia",
    "austria": "austria",
    "belgium": "belgica",
    "bosnia": "bosnia",
    "brazil": "brasil",
    "canada": "canada",
    "cape verde": "cabo verde",
    "colombia": "colombia",
    "croatia": "croacia",
    "curacao": "curazao",
    "czechia": "republica checa",
    "dr congo": "congo",
    "ecuador": "ecuador",
    "egypt": "egipto",
    "england": "inglaterra",
    "france": "francia",
    "germany": "alemania",
    "ghana": "ghana",
    "haiti": "haiti",
    "iran": "iran",
    "iraq": "iraq",
    "ivory coast": "costa marfil",
    "japan": "japon",
    "jordan": "jordania",
    "mexico": "mexico",
    "morocco": "marruecos",
    "netherlands": "paises bajos",
    "new zealand": "nueva zelanda",
    "norway": "noruega",
    "panama": "panama",
    "paraguay": "paraguay",
    "portugal": "portugal",
    "qatar": "qatar",
    "saudi arabia": "arabia saudita",
    "scotland": "escocia",
    "senegal": "senegal",
    "south africa": "sudafrica",
    "south korea": "corea del sur",
    "spain": "españa",
    "sweden": "suecia",
    "switzerland": "suiza",
    "tunisia": "tunez",
    "turkiye": "turquia",
    "uruguay": "uruguay",
    "usa": "estados unidos",
    "uzbekistan": "uzbekistan",
}
